### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by ghost** [MXJosueDev/FishingRod#3]
--- Stack trace ---
  #0 plugins/FishingRod-main.phar/src/FishingRodManager(40): pocketmine\item\ItemIdentifier->__construct(int 346)
  #1 plugins/FishingRod-main.phar/src/Loader(33): fishingrod\FishingRodManager->__construct()
  #2 pmsrc/src/plugin/PluginBase(117): fishingrod\Loader->onEnable()
  #3 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object fishingrod\Loader#26861)
  #5 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25760)
  #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(327): pocketmine\server()
  #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by MXJosueDev** [comment]
I think that now works :)

**Comment by henrythierrydev** [comment]
Now... Yes 😀
